### ISSUE TITLE
Register a new campaign sign up form

### ISSUE THREAD

**Issue by gaton2** [weifund/weifund-dapp-basic#26]

**Comment by gaton2** [comment]
https://drive.google.com/drive/u/0/folders/0B1PYM_IsmGhKYlBxMFdJd0pzVWM

**Comment by rverbee** [comment]
@gaton2 this looks really good. One thing which I thought might be worth speaking through is whether or not the fields here are too specific to an equity raise as opposed to otherwise. Is that so and do we see any issue in proceeding specifically in that direction? Just putting some feedback, not thinking this is a major point.

**Comment by gaton2** [comment]
@rverbee this was created with braid in mind. we should create a separate flow for app tokens since the requirements are different. I'll make that a trello card

**Comment by rverbee** [comment]
Thanks
